export const descriptions ={
    "The Dandelion": "Just steps from Philadelphia's bustling Rittenhouse Square, this inviting bilevel restaurant features a whirlwind of idiosyncratic seating areas, bars, hallways, rooms and nooks, each impeccably fashioned to carry its own personality. Whether you're relaxing with a rare cask ale by the brick fireplace, taking afternoon tea in the Victorian-style dining room or enjoying our famous burger in the ruff-and-tumble “Dog Room,” there's space for everyone. The menu, featuring beloved classics like Welsh rarebit, fish and chips, shepherd's pie and a U.K. cheese board, also features plenty of unexpected surprises. Made-from-scratch puddings and hearty family-style roasts served every Sunday round out one of Philly's most tantalizing dining destinations.",
    "Talula's Garden": "Driven by local ingredients prepared in unbreakable harmony with the season, Talula's Garden is a celebration of cooking the way it ought to be. A partnership with award-winning restaurateur Aimee Olexy, a true farm-to-table ethos inspires Talula's unforgettable approach to food, interpretations of traditional Mid-Atlantic cuisine with a light and modern touch. The indoor-outdoor space exudes a cozy, upbeat vibe, with attention to detail that extends from the gorgeous patio to the cheese bar, home to 'Maítre Fromager' Olexy's standout program. Lush plants and vegetation throughout remind guests that the land is the source of all things wholesome and delicious.",
    "Butcher Bar": "BUTCHER BAR - We invite you to our newest restaurant, “meat lovers and comfort foods” complimented with a bar featuring 16 beers on tap, 6 draft wines, and a whiskey-based cocktail program.",
    "Bao Nine": "Bao Nine is an Asian fushion restaurant inspired by the irresistible Taipei street-style Gua Bao: tender, delicious bao buns. The experience? A soft and dreamy pillow. The feeling? Cloud nine. So we went back to our roots—the city of brotherly love—and created flavor combinations that would reflect and inspire our Philly neighbors from all around the world. What to call this sense of happiness that takes you way beyond the usual? Bao nine, of course. Because we're not just any bun. And that's just how you like it.",
    'Wildberry Pancakes and Cafe': "Established in 2004, Wildberry Café continues to delight guests with scrumptious dishes and welcoming hospitality. We strive to make every visit a memorable dining experience. Our breakfast and lunch menus are inspired by a blend of traditional homemade recipes prepared to please your pallet. We use only fresh, seasonal ingredients that deliver the most delicious flavors and robust goodnes. Our commitment to exceed your expectations starts with our high quality and friendly, personalized service. We go out of our way to ensure every diner's needs are met. It would be our privilege to serve you and your guests. We appreciate your choice in dining with us and aspire to become your favorite way to start the day.At Wildberry Café, we promise to welcome you with smiles and fill your appetite with joy. After all, our home is your home!",
    "Au Cheval":"A diner-style bar and restaurant with a passion for eggs, Au Cheval elevates traditional diner fare. Guests can indulge in dishes ranging from chopped chicken liver and roasted bone marrow, to traditional sandwiches, egg-focused entrees, and the signature cheeseburger. The bar program showcases strong, classic cocktails including the Horse's Neck, Vieux Bonal, and Hemingway's Daiquiri. A robust draught beer list offers a wide range of neighborhood, domestic, and international selections. The dimly lit restaurant, pulsating with a vintage reel-to-reel soundtrack, features dark leather booths, dark wood paneling, and a zinc bar wrapped around the open kitchen.",
    "Lou Malnati's Pizzeria": "Malnati's success comes from our commitment to quality. Every Lou Malnati's pizza is handmade from scratch using the finest and freshest ingredients. Every year, the Malnati team hand selects California vine-ripened tomatoes for the perfect sweet and tangy taste. The exclusive sausage blend is seasoned to our exact specifications. The fresh mozzarella cheese comes from the same small dairy that has supplied Lou Malnati's for over 40 years. And our family's secret recipe for flaky, buttery crust has been passed down from generation to generation. You'll know with every bite that each pizza was made with care and special attention.",
    "Smoque BBQ": "Since opening in Chicago's Old Irving Park neighborhood in late 2006, Smoque has garnered a large and loyal following of BBQ devotees from all over Chicagoland and around the country. We have also attracted interest and praise from local and national media outlets, won many awards, and been consistently ranked among Chicago's best restaurants and the nation's best BBQ spots. Whether dining in or taking out at our original Northwest side location, our Loop location in the Revival Food Hall, or using our catering services, we invite you to stop by soon to see why.",
    "Thursday Kitchen": "Chef Proprietor Kyungmin Kay Hyun’s love for a wide spread of cultures and cuisine makes it hard to place her cooking in a specific category. That is why her own concept of “New Korean” was born. With Chef Kay's South Korean background, French cuisine training, and an exceptional love for Spanish food, Thursday Kitchen offers a unique blend of international elements in ingredients and flavor in a tapas style fashion. You may be wondering, “Why Thursday?” Typically, the weekend seems to start on Fridays, making Thursday night plans uncertain. At Thursday Kitchen, we want to turn that uncertain feeling into a kind of excitement that only we can offer with our quality of food, service, and overall good vibe.",
    "Rubirosa": "Rubirosa is located in the heart of Nolita and its clientele bridges the gap between the old and new neighborhood regulars. Rubirosa's homey and comfortable atmosphere welcomes every occasion, from family-style group dining to drinks and antipasti at our cozy bar.",
    "Jane Restaurant": "Perfectly positioned on the border of Greenwich Village and SoHo, Jane exists at the intersection of elevated and easygoing. Warmly welcoming locals and visitors to our casual, American bistro for nearly 20 years, we’ve got your brunch, lunch and dinner plans covered.",
    "Kimura": "Kimura is a Japanese restaurant specializing in motsunabe(a traditional japanese hotpot), a rich broth made of beef or pork intestines. Alongside the exclusive Japanese hot pot, Kimura also includes sushi, lunch 9-column box, wide selected Japanese beer and sake and traditional Japanese snacks. Kimura is a place where you can enjoy Shabu Shabu (Japanese hot pot), Sukiyaki, Mizutaki Nabe and authentic Japanese food in Manhattan NYC. We are looking forward to you!",
    "Hangari Kalguksu": "Hangari Kalguksu is the destination for Korean comfort food. We specialize in kal-guk-su (hand cut noodle soup) and many other dishes including dumplings, bibimbap and our famous bossam. Our mission is to provide the highest quality food and service at a great value. It doesn't get any simpler than that. Tasty food, great service and value.",
    "Republique": "République, located in Mid-City, is owned by Chefs Walter and Margarita Manzke. Centered in the heart of Los Angeles, the historic building in which it resides was originally erected in 1929 by Charlie Chaplin, and later transformed into the iconic La Brea Bakery and Campanile Restaurant. République builds on this storied past, offering a gastronomic environment imbued with history and grandeur. The space features a casual bakery, café, and bar in the front with a more formal dining area located in the rear, serving a French-inspired menu created daily by our chefs.",
    "Eat This Cafe": "Established in 2012, Eat This Cafe has become a local favorite serving delectable brunches, artisanal sandwiches, specialty salads and daily bottomless mimosas.   We thrive in the hustle and bustle of Hollywood's Theatre Row, surrounded by studios, theaters, and sunshine, providing a relaxing respite from a busy day. We're all about adding a special touch to every dish, from our fresh baked bread delivered daily to our homemade potato chips. Whether you're stopping in for a work lunch or joining us for brunch while sightseeing, we look forward to welcoming you.",
    "Stout Burgers & Beers": "At Stout, we aspire to serve the new-style burger: beef cooked medium rare, organic ground chicken, or a quinoa-based veggie option, dressed with a variety of homemade toppings such as onions cooked down to the sweetness of maple syrup, specialty cheeses, smoky bacon, arugula, and roasted tomatoes. It will be worth dropping in just for a mid-afternoon burger, and a craft beer.",














  }


export const images ={
    "The Dandelion": ["https://s3-media0.fl.yelpcdn.com/bphoto/IszoOQovGzgkCvJXFJEfWA/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/242OpT1PsBGxOLQClXFs7g/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/M5Dwuea2tjbjaZVI6b0Zxw/o.jpg"],
    "Talula's Garden":["https://s3-media0.fl.yelpcdn.com/bphoto/TNtMu58kgijqqvol8tr2WA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/HdnJPmZXACV30xcsledbAA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/PXBAsfKDdpHevIbbcfMyJg/o.jpg"],
    "Butcher Bar": ["https://s3-media0.fl.yelpcdn.com/bphoto/HoggPaiFQpIVKkndQEE0IA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/odw90Jlkm78aRvoY6FbaWQ/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/cNjjCDBFKWLiLJm8Rw59lw/o.jpg"],
    "Maple Japanese Ramen": ["https://s3-media0.fl.yelpcdn.com/bphoto/GijDBAzbzYyFn96-EYTC7Q/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/bgI50S0sgjjBmm7uFsEdRw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/ttP-o6Ozon19pZSe1KXKBA/o.jpg"],
    "Bao Nine": ["https://s3-media0.l.yelpcdn.com/bphoto/k9slbxHSHXxI1gUXvRXV3A/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/KXWRtvYiavg1xUJDB6l9SQ/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/4oUAVEt1jhwXwGlJRKjYtg/o.jpg"],
    "Wildberry Pancakes and Cafe": ["https://s3-media0.fl.yelpcdn.com/bphoto/43XNyVUbPJNtC6IFobGRMw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/__cQUqDXQVUuEuV_UDA8xA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/b3zCSocLYRB9TlrPhJ9G0A/o.jpg"],
    "Au Cheval": ["https://s3-media0.fl.yelpcdn.com/bphoto/a0yhvSJX_6i28iwS9egDFg/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/mPi0IpUKo02JpOqfOnGVFw/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/9uqRTIfJDorNQKIzh1KUZA/o.jpg"],
    "Lou Malnati's Pizzeria": ["https://s3-media0.fl.yelpcdn.com/bphoto/9FiL-9Pbytyg6usOE02lYg/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/RAm_4JAvH4IXkz43V6XRcg/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/8XY-2k4WOVI4ZizhPd_xrw/o.jpg"],
    "Smoque BBQ": ["https://s3-media0.fl.yelpcdn.com/bphoto/wBfhSd0v-aCmJmXgf26f-g/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/PefUyffpKa_HwN93_Q6ItQ/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/Riu91Ap_yvjUstuarFlE_A/o.jpg"],
    "Joe's Seafood, Prime Steak & Stone Crab": ["https://s3-media0.fl.yelpcdn.com/bphoto/CfdCrLQmJ4pw5gQXeF6fHg/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/nUbFDqU0-dnHcljv1xcong/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/bl3ruWkcsXeIlrT3QRKg5g/o.jpg"],
    "Thursday Kitchen": ["https://s3-media0.fl.yelpcdn.com/bphoto/kx6lT4K3kNV8ZUauntNQhA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/OzssPi3tPRae3Fe8LSnrTA/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/pDv_Z0fUWjmdPZMjH1S0xw/o.jpg"],
    "Joe's Shanghai": ["https://s3-media0.fl.yelpcdn.com/bphoto/kNHjVjpJzY47sgilvLFyGw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/fnHr4B2YEnRKlrJ6I7ZF_Q/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/AY3jCGdHL3eFxicQkXWSZg/o.jpg"],
    "Rubirosa": ["https://s3-media0.fl.yelpcdn.com/bphoto/LuSzR8cpVQRofXOT_bMi1A/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/9rzzWu3iqGxC-liqLvWl0Q/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/MMZHXZSfdyJEupS36k8r9A/o.jpg"],
    "Jane Restaurant": ["https://s3-media0.fl.yelpcdn.com/bphoto/J5TWsxXoC_N7KEk2Dp-CwQ/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/V1IX2qagRFLUGpDskPovHQ/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/R1KdVT0EcugFsYITNfNcxg/o.jpg"],
    "Kimura": ["https://s3-media0.fl.yelpcdn.com/bphoto/bUz-DUnMgrY8UqGu3vDxBw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/YVJMqqrzTF6paN5nY3wETw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/h6bWjsY0EVA1F2lZuSJWbw/o.jpg"],
    "L'Antica Pizzeria Da Michele": ["https://s3-media0.fl.yelpcdn.com/bphoto/SCuuHjFSwNpuYxpncVDs9w/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/A4jM2azk3NrH9-n-zHyxow/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/POA34WfBF7HEGGsxe85pBw/o.jpg"],
    "Hangari Kalguksu": ["https://s3-media0.fl.yelpcdn.com/bphoto/X_U65O9YnvMyb42h1BZ0JQ/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/RrIv-PigRNU3yYA-L17J9g/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/tHhlq0BeoJJcvZP7q_4t0A/o.jpg"],
    "Republique": ["https://s3-media0.fl.yelpcdn.com/bphoto/Xy6oJ25E2QUzw_zsBD-dhA/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/yUNfbZeF88v_E0xnO1Neuw/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/xUE4XBtt2iU68s3hv1hXGw/o.jpg"],
    "Eat This Cafe": ["https://s3-media0.fl.yelpcdn.com/bphoto/JnO3SLDimv-99ZAU1SN2ew/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/b7JduF39HdLDLWwmIwWnQQ/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/UUsI98aDZDmMgT_dVRZisA/o.jpg"],
    "Stout Burgers & Beers": ["https://s3-media0.fl.yelpcdn.com/bphoto/k2lUZAeuAgqvfkpS5FxT5Q/o.jpg", "https://s3-media0.fl.yelpcdn.com/bphoto/JNn4mga04qKjaVAtoxTWIw/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/2P-RpKdIQFDgID-Ye942aQ/o.jpg"],








}
